### ISSUE TITLE
UI issues - scrolling, results showing for a split second

### ISSUE THREAD

**Issue by salman1993** [castorini/Anserini#165] opened 2017-03-30 16:23 UTC
Two issues with the speech UI:
- cannot scroll up to the first answer (picture below)
- sometimes, the results are shown for a split second and it goes back to recording screen 

<img width="445" alt="screen shot 2017-03-30 at 12 10 08 pm" src="https://cloud.githubusercontent.com/assets/7154255/24514816/95065744-1543-11e7-8b56-b53be4ed42dc.png">

**Comment by castorini** [comment] 2017-04-01 22:48
Dummy comment to test Slack integration.

**Comment by lintool** [comment] 2017-04-01 22:53
Dummy comment to test Slack integration.

**Comment by rosequ** [comment] 2017-05-05 14:16
@tuzhucheng is this a part of issue #158? I haven't noticed the same issue after your recent PR #174...

**Comment by tuzhucheng** [comment] 2017-05-05 19:13
@rosequ I confirmed the issue in the first bullet is fixed, but I couldn't reproduce the second issue. If you don't observe the second issue then let's close this?

**Comment by rosequ** [comment] 2017-05-05 19:16
@tuzhucheng I don't observe this anymore. @salman1993 let's close it?

**Comment by lintool** [comment] 2017-05-05 19:27
Closing as requested.

**Closed by lintool** 2017-05-05 19:27 UTC
