### ISSUE TITLE
Run baseline on CAR18

### ISSUE THREAD

**Issue by Victor0118** [castorini/anserini#222] opened 2018-06-05 18:02 UTC
MAP                                                                        | BM25   |BM25+RM3| QL     | QL+RM3 |
---------------------------------------------------------------------------|-------:|-------:|-------:|-------:|
test_200  |0.1652  | 0.1317 | 0.1518 | 0.1197
benchmark_train  |0.1630  | 0.1296 | 0.1440 | 0.1117
benchmark_testY1 |  0.1531| 0.1294  | 0.1386 | 0.1120

MRR                                                                        | BM25   |BM25+RM3| QL     | QL+RM3 |
---------------------------------------------------------------------------|-------:|-------:|-------:|-------:|
test_200  |0.2273  | 0.1822 | 0.2085 | 0.1664
benchmark_train  |0.2245  | 0.1841 | 0.2245 | 0.1557
benchmark_testY1 |  0.2292|0.1915  | 0.2042 | 0.1648

The results on `test_200` and `benchmark_train` datasets are similar to last year.  https://arxiv.org/pdf/1705.04803.pdf

The BM25 on the `train` dataset is still running (have been running for 10h).
~~We don't have the label of `benchmark_test` so I did not report the result. We can use it as a starting point for NN models.~~ We have it now!

Currently, I use `topics` files in `test_200 ` and `benchmark_train ` datasets as query file and `*.hierarchical.qrels` as the qrels file. For `train` dataset, there is no `topic` file. So I extract it from the `*.hierarchical.qrels`. This might be correlated with the issue #9 since we are not sure which file covers all the queries. But through our preliminary investigation, the difference is minor and we will pay attention to it later if we need it.

**Comment by lintool** [comment] 2019-06-06 02:02
I'm closing this for now. We'll probably want to build CAR18 regressions at some point in time, but the results are likely going to be very different from above, since codebase has evolved quite a bit...

**Closed by lintool** 2019-06-06 02:02 UTC
