### ISSUE TITLE
Documentation enhancement

### ISSUE THREAD

**Issue by twelveth** [castorini/anserini#1111] opened 2020-04-21 13:40 UTC
Hi.
This is not an issue, but maybe an enhancement request.
I'm trying to use anserini for custom collection, and it's rather hard for me to figure out how to build pipeline from scratch.

For example, however there are a lot of scripts about how to reproduce some particular results, I couldn't find any information about format of document, which anserini takes as input to index custom collection. Also I need to spend enough time to find explaination of all the arguments the engine uses for searching or indexing.

It would be wonderful if you describe all the abilites of your engine with readthedocs or something similar, because now Getting Started section doesn't provide much useful information about pipeline building.

**Comment by lintool** [comment] 2020-04-21 13:43
Hi @twelveth thanks for your feedback. Yes, better documentation is indeed on our TODO list!

In the meantime, the quickest way to get started would be to write a simple script (e.g., in Python) to covert your collection into the MS MACRO JSON format (which is fairly simple), and then you can reuse the MS MARCO pipeline: https://github.com/castorini/anserini/blob/master/docs/experiments-msmarco-passage.md

**Comment by twelveth** [comment] 2020-04-21 15:20
Thank you for your answer @lintool. Can you explain this format please or provide me with link to its description? On TREC DL page I've found only tsv format explaination, nothing about json, but dataset size is rather big (22Gb) to download it just to find out its structure.

**Comment by egzhbdt** [comment] 2020-05-10 01:39
Hi,
We kept this documentation for our workflow, basically a summarization of this thread. In case someone else in the future wants a quick start. 

## Indexing and Retrieving a Custom Collection 

Anserini supports indexing and retrieving a custom collection. 

If you are looking to build a search pipeline with such collection, you might want to try with the following steps. The use case is suitable for search pipelines with
* Essential, comprehensible search capability (BM25 similarity scoring) at first, and
* Flexible, programmable configurations for future requirements.

### Quickstart 

<b>Prepare your custom collection in Anserini input.</b> 
    
* Write a script (e.g. like [this one](https://github.com/castorini/anserini/blob/master/src/main/python/msmarco/convert_collection_to_jsonl.py)) to convert the collection into the MS MACRO JSON format. 
* The collection will become a directory with <code>.json</code> files. Inside each <code>.json</code> file is either 
	* A JSON Object (one document) or,

		    {
		        "id": "doc1",
		        "contents": "this is the contents."
		    }
		    
	* A JSON Array (multiple documents). 
		 
		    [
		        {
		            "id": "doc1",
		            "contents": "this is the contents 1."
		        },
		        {
		            "id": "doc2",
                    "contents": "this is the contents 2."
		        }
		    ]

		    
* In this way, your data preparation step aligns with the [MS Marco pipeline](https://github.com/castorini/anserini/blob/master/docs/experiments-msmarco-passage.md#data-prep).

<b>Prepare a queries file for your collection</b> 
* One query per line. Each line has the format of `qid[\t]query[\n]`. 

<b>Run the indexing step from the [MS MARCO pipeline](https://github.com/castorini/anserini/blob/master/docs/experiments-msmarco-passage.md)</b>
* This step resembles below line in above documentation. 
    > index the docs as a JsonCollection using Anserini
    
* That is, you would use an indexing command such as below, 
    
    ```
    sh ./target/appassembler/bin/IndexCollection -collection JsonCollection \
     -generator DefaultLuceneDocumentGenerator -threads 9 -input [YOUR_JSON_COLLECTION_PATH] \
     -index [INDEX_PATH] -storePositions -storeDocvectors -storeRaw 
    ```
<b>Run the retrieval step from the [MS MARCO pipeline](https://github.com/castorini/anserini/blob/master/docs/experiments-msmarco-passage.md#retrieving-and-evaluating-the-dev-set)</b> 
* This step resembles below line in above documentation.   
    > We can now retrieve this ...

* That is, you would use a retrieving command such as below. The output is a <code>.tsv</code> file of top-hit retrieval results.  
    ```
    python ./src/main/python/msmarco/retrieve.py --hits [NUM_OF_HITS_AS_RESULTS] --threads 1 \
     --index [INDEX_PATH] --qid_queries [QUERY_FILE_PATH] \
     --output [OUTPUT_PATH]
    ```
<b>Finally, screen retrieval results, and modify above pipeline to fit your workflow!</b>

**Comment by lintool** [comment] 2020-05-10 12:08
hi @egzhbdt - thanks, this is great!

Can you just dump all the contents above into a file, something like `docs/custom-collections.md` and send a PR? It'd be great to get this merged directly into the repo docs!

**Comment by MarcosFP97** [comment] 2020-06-05 10:40
Hi,
I am also trying to index a custom collection, but in my case I have a bunch of warc.gz files. I assume that the procedure must be the same described as @egzhbdt, but adapting the first Python script or is there any other pipeline already prepared to work with this kind of files? Since they are very common in TREC tasks...
Thanks in advance!

**Comment by lintool** [comment] 2020-06-05 10:43
For ClueWeb collections, we already have: https://github.com/castorini/anserini/blob/master/docs/regressions-cw09b.md and https://github.com/castorini/anserini/blob/master/docs/regressions-cw12b13.md

Linked from the front page.

**Comment by MarcosFP97** [comment] 2020-06-05 12:55
Oh perfect, thank you. I have been trying to follow the ClueWeb09 example and if I read the log it finds me the n number of warc.gz files that I am trying to index, but it finishes the process returning "Total 0 documents indexed"... This is the command that I am using:

nohup sh target/appassembler/bin/IndexCollection -collection ClueWeb09Collection -input /path/to/my-bunch-of-files -index indexes/lucene-index.cw09.pos+docvectors+raw -generator DefaultLuceneDocumentGenerator -threads 44 -storePositions -storeDocvectors -storeRaw &>logs/log.cw09b.pos+docvectors+rawdocs

Thanks a lot again

**Comment by lintool** [comment] 2020-06-05 13:04
Does it find the correct number of WARCs? What does your cw19 directory look like? Describe or copy/paste snippet from `ls` command.

**Comment by MarcosFP97** [comment] 2020-06-05 13:24
Yes, it finds exactly 50 WARCs.
ls for input path returns:
$ ls
CC-NEWS-20200101023937-00188.warc.gz  
CC-NEWS-20200102061500-00198.warc.gz  
CC-NEWS-20200102233440-00208.warc.gz  
CC-NEWS-20200103180051-00218.warc.gz  
CC-NEWS-20200104162404-00228.warc.gz
CC-NEWS-20200101061553-00189.warc.gz  
CC-NEWS-20200102083050-00199.warc.gz  
...

**Comment by lintool** [comment] 2020-06-05 13:27
I see you're trying to do this: https://github.com/castorini/anserini/issues/1259
It's on our todo list also.

I bet there are differences between these WARCs and the ClueWeb ones. Try the ClueWeb12 API.

**Comment by MarcosFP97** [comment] 2020-06-05 14:46
Yes, that's the exact collection I am using.
I have just tried the ClueWeb12 API specifying `-collection ClueWeb12Collection`, but the result is the same: 0 indexed docs and the rest, unindexable.
So, I think the only option left is wait for the CommonCrawlCollection that you are planning to do.

**Comment by lintool** [comment] 2020-06-05 14:50
Or you can try to debug and send a PR!

**Comment by MarcosFP97** [comment] 2020-06-05 21:00
I will try me best to debug it then :+1:

**Comment by lintool** [comment] 2020-09-08 15:46
"How Do I Search My Own Documents?" is at: https://github.com/castorini/pyserini/#how-do-i-search-my-own-documents

Closing issue.

**Closed by lintool** 2020-09-08 15:46 UTC
