### ISSUE TITLE
Building anserini on MacOS

### ISSUE THREAD

**Issue by Nebu0528** [castorini/anserini#2445] opened 2024-04-06 18:18 UTC
![image](https://github.com/castorini/anserini/assets/85001440/20e0cdea-45e7-49f5-b3d9-c25e682e1759)
I am builing anserini using JDK 21 and maven 3.9.6 as mentioned in the updated readme, however it is failing when trying to connect to the link as shown in the screenshot.

**Comment by lintool** [comment] 2024-04-06 18:26
Seems like a transient error... try again?

**Comment by Nebu0528** [comment] 2024-04-06 20:14
The issue still persists, but due to the runtime, is there something you'd recommend? I can provide an error log if you'd like as well.

![image](https://github.com/castorini/anserini/assets/85001440/15c7b7e4-7255-4fcc-a3d4-d22fc801f172)

**Comment by lintool** [comment] 2024-04-06 20:21
Hrm... seems to work for me... can you provide more detailed error log?

**Comment by Nebu0528** [comment] 2024-04-06 20:27
[ERROR] Tests run: 3, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.013 s <<< FAILURE! - in io.anserini.index.PrebuiltIndexTest
[ERROR] io.anserini.index.PrebuiltIndexTest.testUrls  Time elapsed: 0.013 s  <<< ERROR!
java.lang.RuntimeException: Error connecting to https://github.com/castorini/anserini-data/raw/master/CACM/lucene-index.cacm.20221005.252b5e.tar.gz
	at io.anserini.index.PrebuiltIndexTest.testUrls(PrebuiltIndexTest.java:52)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:316)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:240)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:214)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:155)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:385)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:507)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:495)
Caused by: java.net.UnknownHostException: example.com
	at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:567)
	at java.base/java.net.Socket.connect(Socket.java:751)
	at java.base/java.net.Socket.connect(Socket.java:686)
	at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:183)
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:531)
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:636)
	at java.base/sun.net.www.http.HttpClient.<init>(HttpClient.java:280)
	at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:386)
	at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:408)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1304)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1237)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1123)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:1052)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1675)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1599)
	at java.base/java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:531)
	at io.anserini.index.PrebuiltIndexTest.testUrls(PrebuiltIndexTest.java:50)
	... 26 more

**Comment by lintool** [comment] 2024-04-06 20:45
This works fine for me... the URL does appear to be valid.

```
wget  https://github.com/castorini/anserini-data/raw/master/CACM/lucene-index.cacm.20221005.252b5e.tar.gz
```

Try that on your end and see what you get?

**Comment by Nebu0528** [comment] 2024-04-06 20:57
it works, i tried running the mvn command after that but it is giving the same issue from the screenshot

**Comment by lintool** [comment] 2024-04-06 20:59
Try removing `~/.cache/anserini` and `~/.cache/pyserini`. If that still doesn't work, try a fresh clone.

**Comment by Nebu0528** [comment] 2024-04-07 00:44
Same issue from doing both:

If this helps I got jdk21 from the link below for MacOS:
https://www.oracle.com/ca-en/java/technologies/downloads/#jdk21-mac

and maven 3.9.6 from: https://maven.apache.org/download.cgi

Attached is the textfile of the error report: io.anserini.index.PrebuiltIndexTest.txt
[io.anserini.index.PrebuiltIndexTest copy.txt](https://github.com/castorini/anserini/files/14895390/io.anserini.index.PrebuiltIndexTest.copy.txt)

**Comment by Gelardinio** [comment] 2024-04-07 04:51
Pretty sure line 48 of PreBuiltIndexTest.java needs to be changed from

`final URL requestUrl = new URI("http://example.com").toURL();`

to

`final URL requestUrl = new URI(url).toURL();`

Otherwise errors are caused within builds since the url being tested isn't used and http://example.com/ is an invalid url.

**Comment by lintool** [comment] 2024-04-07 12:15
Pretty sure http://example.com/  is a valid URL:

```
$ curl -I https://example.com/
HTTP/2 200 
content-encoding: gzip
accept-ranges: bytes
age: 7987
cache-control: max-age=604800
content-type: text/html; charset=UTF-8
date: Sun, 07 Apr 2024 12:14:26 GMT
etag: "3147526947"
expires: Sun, 14 Apr 2024 12:14:26 GMT
last-modified: Thu, 17 Oct 2019 07:18:26 GMT
server: ECS (dce/26D5)
x-cache: HIT
content-length: 648
```

... but, try changing it to something like https://uwaterloo.ca/ and see what happens?

**Comment by Gelardinio** [comment] 2024-04-07 12:37
Yeah it does look valid thought it wasn't. Also not sure why it would be checking example.com for all urls under IndexInfo as it looks like none of the urls in IndexInfo is checked for from this test:

```java
 // test url validity
  @Test
  public void testUrls() {
    for (IndexInfo info : IndexInfo.values()) {
      for (String url : info.urls) {
        // check each url status code is 200
        try {
          final URL requestUrl = new URI("http://example.com").toURL();
          final HttpURLConnection con = (HttpURLConnection) requestUrl.openConnection();
          assertEquals(200, con.getResponseCode());
        } catch (IOException e) {
          throw new RuntimeException("Error connecting to " + url, e);
        } catch (Exception e) {
          throw new RuntimeException("Malformed URL: " + url, e);
        }
      }
    }
  }
  ```

**Comment by lintool** [comment] 2024-04-07 12:48
Yea, good point... maybe that was supposed to be a placeholder that didn't get fixed. It _would_ make sense to check all the URLs, as intended. @Gelardinio would you be willing to send a PR to fix?

Always good to fix janky code, but still doesn't address the original question of why the tests are failing?

**Comment by Gelardinio** [comment] 2024-04-07 13:19
Sounds good. I don't think I have the permissions to make a PR yet since I just started the onboarding yesterday. To answer the original question it's probably because some rate limit is probably being reached with http://example.com because we're sending a request to it for every url in IndexInfo.

**Comment by lintool** [comment] 2024-04-07 13:21
re: permissions - clone the repo and send PR that way?

**Comment by Gelardinio** [comment] 2024-04-07 13:26
Didn't seem to work when I tried. Will try again once I'm back later today.

**Comment by Gelardinio** [comment] 2024-04-09 01:01
Looks like I don't have permissions to make a pr with my branch I think.

**Comment by lintool** [comment] 2024-04-09 01:02
> Looks like I don't have permissions to make a pr with my branch I think.

Clone the repo, then branch off your clone, then send PR?

**Comment by Gelardinio** [comment] 2024-04-09 01:05
I believe that's what I'm doing:

<img width="783" alt="Screenshot 2024-04-08 at 9 05 03 PM" src="https://github.com/castorini/anserini/assets/29520085/e02f523c-aa47-46ca-a406-79a9a04db8b5">

**Comment by lintool** [comment] 2024-04-09 01:06
No, you're trying to branch off the main anserini repo. 

You need to fork first: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/fork-a-repo

**Comment by Gelardinio** [comment] 2024-04-09 01:24
My bad, this should work https://github.com/castorini/anserini/pull/2449

**Comment by lintool** [comment] 2024-04-09 01:38
hi @Gelardinio thanks for your PR. merged.

**Closed by lintool** 2024-04-09 01:38 UTC
