### ISSUE TITLE
Failed tests: WashingtonPostDocumentTest.test

### ISSUE THREAD

**Issue by catenamatteo** [castorini/Anserini#441] opened 2018-09-27 11:39 UTC
The test in subject fails when doing mvn clean install appassembler:assemle

Running io.anserini.collection.WashingtonPostDocumentTest
NOTE: reproduce with: ant test  -Dtestcase=WashingtonPostDocumentTest -Dtests.method=test -Dtests.seed=1F9ADA48760EEFFA -Dtests.locale=da-DK -Dtests.timezone=Australia/Melbourne -Dtests.asserts=true -Dtests.file.encoding=ANSI_X3.4-1968
NOTE: leaving temporary files on disk at: /tmp/io.anserini.collection.WashingtonPostDocumentTest_1F9ADA48760EEFFA-001
NOTE: test params are: codec=Asserting(Lucene62): {}, docValues:{}, maxPointsInLeafNode=1872, maxMBSortInHeap=6.402142198457144, sim=ClassicSimilarity, locale=da-DK, timezone=Australia/Melbourne
NOTE: Linux 4.4.0-128-generic amd64/Oracle Corporation 1.8.0_181 (64-bit)/cpus=16,threads=1,free=238009520,total=430440448
NOTE: All tests run in this JVM: [TweetEndToEndTest, TrecEndToEndTest, IndexerTest, SdmQueryTest, SCQFeatureExtractorTest, BM25FeatureExtractorTest, SCSFeatureExtractorTest, UnigramFeaturesTest, LoadFeatureExtractorFromFileTest, TFIDFFeatureExtractorTest, DocSizeFeatureExtractorTest, TermFrequencyFeatureExtractorTest, BigramFeaturesTest, PMIFeatureExtractorTest, FeatureExtractorChainFromJsonTest, AvgIDFFeatureExtractorTest, ICTFFeatureExtractorTest, DocumentTest, TrecwebDocumentTest, JsonDocumentArrayTest, WikipediaArticleTest, JsonDocumentObjectTest, WashingtonPostDocumentTest]
Tests run: 2, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.063 sec <<< FAILURE! - in io.anserini.collection.WashingtonPostDocumentTest
test(io.anserini.collection.WashingtonPostDocumentTest)  Time elapsed: 0.03 sec  <<< FAILURE!
org.junit.ComparisonFailure: expected:<...ght can ease jet lag[???]s effects before and...> but was:<...ght can ease jet lag[?]s effects before and...>
	at __randomizedtesting.SeedInfo.seed([1F9ADA48760EEFFA:97CEE592D8F28202]:0)
	at org.junit.Assert.assertEquals(Assert.java:115)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at io.anserini.collection.WashingtonPostDocumentTest.test(WashingtonPostDocumentTest.java:83)

**Comment by lintool** [comment] 2018-09-27 11:48
Odd... CI shows green: https://travis-ci.org/castorini/Anserini

Is this on master?

Looking at the error trace:

> <<< FAILURE!
org.junit.ComparisonFailure: expected:<...ght can ease jet lag[???]s effects before and...> but was:<...ght can ease jet lag[?]s effects before and...>

Difference seems to be the apostrophe... some unicode encoding problem on the source?

**Comment by catenamatteo** [comment] 2018-09-27 12:05
Maybe a locale setting problem? Let me know if there is a command to check this, so I can help. Distro is Ubuntu 16.04.5 LTS (GNU/Linux 4.4.0-128-generic x86_64). 

The code should be from the master branch, I simply did git clone https://github.com/castorini/Anserini.git

**Comment by lintool** [comment] 2018-09-27 12:13
I am unable to reproduce?

> mvn -Dtest=io.anserini.collection.WashingtonPostDocumentTest test 

This doesn't seem to work for me (don't know where ant is coming from?):

> NOTE: reproduce with: ant test -Dtestcase=WashingtonPostDocumentTest -Dtests.method=test -Dtests.seed=1F9ADA48760EEFFA -Dtests.locale=da-DK -Dtests.timezone=Australia/Melbourne -Dtests.asserts=true -Dtests.file.encoding=ANSI_X3.4-1968

But this looks suspicious:

> -Dtests.file.encoding=ANSI_X3.4-1968

This would jive with the encoding issues above... I believe the source files are unicode.

**Comment by diegoceccarelli** [comment] 2018-09-27 12:16
You can change the maven to setup the encoding if it is not doing it
already..

**Comment by catenamatteo** [comment] 2018-09-28 14:22
my `locale` was
`LANG=en_US.UTF-8
LANGUAGE=
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
`
The test in subject succeeds with `export LC_ALL=en_US.UTF-8`. Can you do something similar (and more portable) by editing the pom.xml as suggested by @diegoceccarelli? i.e., to force the setup to the right encoding

**Comment by lintool** [comment] 2018-10-12 15:05
Fixed by #454

**Closed by lintool** 2018-10-12 15:05 UTC
