### ISSUE TITLE
Implement learning to rank features in Macdonald (CIKM 2012)

### ISSUE THREAD

**Issue by claclark** [castorini/anserini#45] opened 2015-11-04 18:55 UTC
@lintool:

We need to add query features from Macdonald et al., CIKM 2012

"On the Usefulness of Query Features for Learning to Rank"

http://www.dcs.gla.ac.uk/~craigm/publications/macdonald12queryf.pdf

**Comment by ABDULAZIZALQATAN** [comment] 2019-05-07 05:57
Dear Sir 
I am trying to run Anserini Commands on TREC CommonCore 2017
[https://github.com/castorini/anserini/blob/master/docs/experiments-core17.md]

The problem is that the main class cannot be detected 

![1](https://user-images.githubusercontent.com/47518534/57275075-38639880-7095-11e9-8643-5a656225a711.jpg)
It might be from here "Class path" or somthing relted to it 

![4](https://user-images.githubusercontent.com/47518534/57275104-503b1c80-7095-11e9-9158-b2839215b8f2.jpg)

**Comment by lintool** [comment] 2021-03-21 11:56
Since we have a new reworked LTR pipeline, closing now.

**Closed by lintool** 2021-03-21 11:56 UTC
