### ISSUE TITLE
IndexUtils fails with collection indexed with my own Lucene Indexer

### ISSUE THREAD

**Issue by it21208** [castorini/anserini#652] opened 2019-05-20 18:05 UTC
I have indexed a collection using my own lucene indexer (not Anserini indexer) and then I am trying to use the IndexUtils from Anserini to print some stats about the collection with this command: 
$  target/appassembler/bin/IndexUtils -index pubmedindex -stats 
Where pubmedindex is the folder that contains the indexed collection. Below is a screenshot of what I get back.
![Screenshot from 2019-05-20 18-43-18](https://user-images.githubusercontent.com/11080193/58041130-3850a780-7b2f-11e9-9e0d-1f016749c412.png)
Also when I try to do other things with IndexUtils params such as -dumpAllDocids NONE I get the following: 
![Screenshot from 2019-05-20 18-48-30](https://user-images.githubusercontent.com/11080193/58041466-13a8ff80-7b30-11e9-9567-3b7573df24b4.png)
I took a screenshot comparing the contents of the folder of an indexed collection from one of your examples 'lucene-index.core17.pos+docvectors+rawdocs' and underneath the contents of the indexed pubmed collection with my own indexer, they look similar. Do you know if I am missing something in my indexed collection and if yes does Anserini have any tools to add the missing data or bypass this? 
![Screenshot from 2019-05-20 00-07-29](https://user-images.githubusercontent.com/11080193/58041827-fe80a080-7b30-11e9-94be-2997f5780774.png)
Thank you

**Comment by Peilin-Yang** [comment] 2019-05-21 14:44
Can you please tell us how did you build your own Lucene index?
Specifically, what are the fields you had used? 
What I can see is that https://github.com/castorini/anserini/blob/master/src/main/java/io/anserini/index/IndexUtils.java#L157 reads the terms in the `contents` field. 
My guess is that there is no such field in your index

**Comment by lintool** [comment] 2019-05-21 18:20
Anserini index inspection tools are really only designed to be used on indexes created by Anserini, to make sure that the metadata (e.g., field definitions) are correct.

If you are looking for a more general Lucene index inspection tool, I can recommend Luke:
https://medium.com/@mocobeta/luke-become-an-apache-lucene-module-as-of-lucene-8-1-7d139c998b2

**Comment by it21208** [comment] 2019-05-23 11:17
> Can you please tell us how did you build your own Lucene index?
> Specifically, what are the fields you had used?
> What I can see is that https://github.com/castorini/anserini/blob/master/src/main/java/io/anserini/index/IndexUtils.java#L157 reads the terms in the `contents` field.
> My guess is that there is no such field in your index

Thanks for the reply. So I added some fields in order to much the fields that I have in my index and then I managed to run successfully the stats command as well as the printTermInfo 
![Screenshot from 2019-05-23 12-05-33](https://user-images.githubusercontent.com/11080193/58248161-539bfc80-7d53-11e9-8668-3fc84067ab4f.png)
![Screenshot from 2019-05-23 12-08-36](https://user-images.githubusercontent.com/11080193/58248310-aecdef00-7d53-11e9-840c-a61eca939010.png)
 But I am still facing an issue with some other options for example the target/appassembler/bin/IndexUtils -index indexed_collection_folder **-dumpAllDocids NONE** 
The above command returns the following message: 
>  All Documents IDs are output to: indexed_collection_folder.allDocids.txt

 but this file is empty it has 0 bytes. And I am wondering why this is happening could it possibly be that the docnum String field has in it's indexOption: DOCS and not DOCS_AND_FREQS_AND_POSITIONS?

**Comment by lintool** [comment] 2019-05-23 13:04
`-dumpAllDocids` is looking for a field that doesn't exist in your index, see:
https://github.com/castorini/anserini/blob/master/src/main/java/io/anserini/index/IndexUtils.java#L298

**Comment by it21208** [comment] 2019-05-23 13:30
> `-dumpAllDocids` is looking for a field that doesn't exist in your index, see:
> https://github.com/castorini/anserini/blob/master/src/main/java/io/anserini/index/IndexUtils.java#L298

Hello thanks for the reply. I had noticed the getAllDocids method, and I also changed the FIELD_ID field (both in the IndexUtils class but also in the LuceneDocumentGenerator class where the construction of the document takes place) with my corresponding field  FIELD_DOCNUM (which is exactly the same StringField) and also with another field of mine (which also exists in my index) that contains everything named FIELD_ALL , however nothing changed in both scenarios. I tried to debug the program by printing some values in the method you mentioned i.e. scoreDocs it's empty so it doesn't enter the loop further down in the method to build the StringBuilder. Do you think that my problem may be in the LuceneDocumentGenerator 

> document.add(new StringField(FIELD_DOCNUM, id, Field.Store.YES));  

Perhaps I have to explicitly set setStoreTermVectorPositions or fieldType.setIndexOptions for when adding the id, just like you do in all other fields. Although I doubt this might actually do me any good. Or perhaps there is a way to access the FIELD_DOCNUM field which is also contained inside the FIELD_ALL. I can provide screenshots if I am not describing something correctly.

**Comment by it21208** [comment] 2019-05-23 13:39
Also, something additional which I noticed with other option that involve specific docids is that the docid is an integer and I receive error message saying docid entered is -1 and it should be greater than zero and smaller than reader.maxDoc() which correctly finds the total number of documents indexed. Is there a possibility that I might be facing an incompatibility/mismatch between data types (i.e. int, String) of my docnum.

**Comment by lintool** [comment] 2019-05-23 13:43
tbh, if you're thinking of using Anserini beyond just `IndexUtils` (take advantage of our models, etc.) - I would prefer if you just hooked into our entire pipeline - build an instance of a `Collection` so you can use our indexer, ranking models, etc.

It looks like you're trying to index a MEDLINE collection? We'd welcome a contribution for those corpora.

I'm not sure what your goals are, but even if it's sure trying to replicate a previous result, this might be a nice paper for the ECIR reproducibility tracks.

**Comment by lintool** [comment] 2019-05-31 22:16
Seeing no follow up, closing.

**Closed by lintool** 2019-05-31 22:16 UTC
