### ISSUE TITLE
Test failures (Java 13, encoding issues)

### ISSUE THREAD

**Issue by cmacdonald** [castorini/anserini#1198] opened 2020-05-15 12:35 UTC
```
(base) [craigm@trhead anserini]$export JAVA_HOME=/local/trmaster/opt/jdk-13.0.2
(base) [craigm@trhead anserini]$which mvn
alias mvn='/local/trmaster/opt/apache-maven-3.3.9/bin/mvn'
	/local/trmaster/opt/apache-maven-3.3.9/bin/mvn
(base) [craigm@trhead anserini]$mvn clean package appassembler:assemble install
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building Anserini 0.9.3-SNAPSHOT
[INFO] ------------------------------------------------------------------------
Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-gpg-plugin/1.6/maven-gpg-plugin-1.6.pom
Downloaded: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-gpg-plugin/1.6/maven-gpg-plugin-1.6.pom (6 KB at 5.2 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-gpg-plugin/1.6/maven-gpg-plugin-1.6.jar
Downloaded: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-gpg-plugin/1.6/maven-gpg-plugin-1.6.jar (47 KB at 337.4 KB/sec)
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ anserini ---
[INFO] Deleting /users/tr.craigm/src/anserini/target
[INFO] 
[INFO] --- jacoco-maven-plugin:0.8.2:prepare-agent (default) @ anserini ---
[INFO] argLine set to -javaagent:/users/craigm/.m2/repository/org/jacoco/org.jacoco.agent/0.8.2/org.jacoco.agent-0.8.2-runtime.jar=destfile=/users/tr.craigm/src/anserini/target/jacoco.exec
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ anserini ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 205 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.8.1:compile (default-compile) @ anserini ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 151 source files to /users/tr.craigm/src/anserini/target/classes
[WARNING] bootstrap class path not set in conjunction with -source 11
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ anserini ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 42 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.8.1:testCompile (default-testCompile) @ anserini ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 94 source files to /users/tr.craigm/src/anserini/target/test-classes
[WARNING] bootstrap class path not set in conjunction with -source 11
[INFO] 
[INFO] --- maven-surefire-plugin:2.12.4:test (default-test) @ anserini ---
[INFO] Surefire report directory: /users/tr.craigm/src/anserini/target/surefire-reports

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:513)
	at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:525)
Caused by: java.lang.RuntimeException: Class java/lang/UnknownError could not be instrumented.
	at org.jacoco.agent.rt.internal_28bab1d.core.runtime.ModifiedSystemClassRuntime.createFor(ModifiedSystemClassRuntime.java:140)
	at org.jacoco.agent.rt.internal_28bab1d.core.runtime.ModifiedSystemClassRuntime.createFor(ModifiedSystemClassRuntime.java:101)
	at org.jacoco.agent.rt.internal_28bab1d.PreMain.createRuntime(PreMain.java:55)
	at org.jacoco.agent.rt.internal_28bab1d.PreMain.premain(PreMain.java:47)
	... 6 more
Caused by: java.lang.NoSuchFieldException: $jacocoAccess
	at java.base/java.lang.Class.getField(Class.java:2000)
	at org.jacoco.agent.rt.internal_28bab1d.core.runtime.ModifiedSystemClassRuntime.createFor(ModifiedSystemClassRuntime.java:138)
	... 9 more
*** java.lang.instrument ASSERTION FAILED ***: "result" with message agent load/premain call failed at JPLISAgent.c line: 422
FATAL ERROR in native method: processing of -javaagent failed, processJavaStart failed
```

**Comment by lintool** [comment] 2020-05-15 12:38
Seems like a known issue: https://github.com/jacoco/jacoco/issues/828

**Comment by littlewine** [comment] 2020-06-17 12:34
I faced a similar issue with Java 11:

```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  31.161 s
[INFO] Finished at: 2020-06-17T12:17:05+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.12.4:test (default-test) on project anserini: There are test failures.
[ERROR]
[ERROR] Please refer to /home/akrasak/anserini/target/surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
```

Changing the JaCoCo version to `0.8.3` worked for me (build+unit tests passed). Maybe update it for the next version of anserini?

**Comment by lintool** [comment] 2020-06-17 13:23
Hrm, I'm on Java 11:

```
$ java -version
java version "11.0.4" 2019-07-16 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.4+10-LTS)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.4+10-LTS, mixed mode)
```

... not having these issues. I think the entire team is on Java 11... wondering if anyone else is?

**Comment by littlewine** [comment] 2020-06-18 10:04
Im in the same java version.
Seems that changing the jacoco version to `0.8.3` didnt solve the problem, the tests seem to be failing again.
I tried forcing a surefire update to v `3.0.0-M1` (in stackoverflow they mentioned it solved the problem) but didn't work
Any idea what's wrong?

```
[INFO] Results:
[INFO]
[ERROR] Failures:
[ERROR]   TopicReaderTest.testNonEnglishTopics:502 expected:<[?????????????????]> but was:<[???????????????????????????????????????????????????]>
[ERROR]   TopicReaderTest.testNonEnglishTopics_TopicIdsAsStrings:560 expected:<[?????????????????]> but was:<[???????????????????????????????????????????????????]>
[INFO]
[ERROR] Tests run: 288, Failures: 2, Errors: 0, Skipped: 0
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  34.638 s
[INFO] Finished at: 2020-06-18T11:59:42+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M1:test (default-test) on project anserini: There are test failures.
[ERROR]
[ERROR] Please refer to /home/akrasak/anserini/target/surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
(base) -bash-4.2$
```

**Comment by cmacdonald** [comment] 2020-06-18 10:07
Looks like an encoding problem. What is your LANG setting?

**Comment by littlewine** [comment] 2020-06-18 10:09
oh okay... 
I do indeed get some complaints every time I log in to the server:
`-bash: warning: setlocale: LC_CTYPE: cannot change locale (UTF-8): No such file or directory`

How can I check this?

**Comment by lintool** [comment] 2020-06-18 13:13
Yes, locale issues are weird and hard to debug - if you figure it out, please report back here so we have a record of it.

FWIW, this doesn't seem like a critical issue... to skip tests:

```
https://github.com/castorini/anserini/blob/master/bin/qbuild.sh
```

**Comment by littlewine** [comment] 2020-06-18 15:12
I eventually figured it out, many thanks to @cmacdonald for the awesome debugging skills and to you Jimmy for the quick response. 
It turns out that the problem was caused by my local machine (OSX) where the locale was not set properly.
I just had to add the following lines to my *local* `.bash_profile`:
```
export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8
```

**Comment by lintool** [comment] 2020-06-18 15:16
I changed the title of the issue to make it a bit easier to find in the future. Glad everything go resolved!

Closing issue.

**Closed by lintool** 2020-06-18 15:16 UTC
