### ISSUE TITLE
java.lang.OutOfMemoryError: Java heap space

### ISSUE THREAD

**Issue by twelveth** [castorini/anserini#1315] opened 2020-07-09 09:24 UTC
I've got a 44Gb index and about 18000 queries. And when I try to run `retrieve.py` with 4 threads, I always get error `java.lang.OutOfMemoryError: Java heap space`, but only 10/32Gb RAM is used (with free 32Gb swap).

**Comment by lintool** [comment] 2020-07-09 11:21
The issue is that for multithreaded search, to make synchronization easier, all query results are stored in memory and then serialized to disk at the end. Try searching fewer queries.

Alternatively, pyjnius allows you to set underlying JVM options:
https://pyjnius.readthedocs.io/en/stable/api.html

e.g., something like:

```python
import jnius_config
jnius_config.add_options('-Xrs', '-Xmx4096')
jnius_config.set_classpath('.', '/usr/local/fem/plugins/*')
import jnius
```

**Comment by twelveth** [comment] 2020-07-09 12:20
But I have `--hits=10` and the whole retrieval output file is only a couple MBs.

**Comment by lintool** [comment] 2020-07-09 13:13
Dunno then.. maybe the default setting isn't particularly ideal?

**Comment by twelveth** [comment] 2020-07-09 13:47
So, what setting should I use? 
I used [this](https://github.com/castorini/anserini/issues/1111#issuecomment-626259434) as example. I copied `retrieve.py` to my project and changed it a bit, so it could also use qld retrieval strategies. But I have such problem with bm25 too.

**Comment by lintool** [comment] 2020-07-09 15:31
Try fewer queries at once.

**Comment by lintool** [comment] 2020-07-14 16:31
@twelveth any further updates on this?

**Comment by twelveth** [comment] 2020-07-14 17:34
Yeah, I split all queries in a half and processed these parts sequentially, all in 4 threads. There were no such problems. But if I process all of them in one file, it either gets stuck on 60-80% or gives aforementioned error.

**Comment by lintool** [comment] 2020-07-14 17:36
This would suggest that what I mentioned above is the culprit:

> The issue is that for multithreaded search, to make synchronization easier, all query results are stored in memory and then serialized to disk at the end. Try searching fewer queries.

Closing issue.

**Closed by lintool** 2020-07-14 17:36 UTC
