### ISSUE TITLE
Indexing WaPo log shows no progress

### ISSUE THREAD

**Issue by Chriskamphuis** [castorini/anserini#795] opened 2019-09-07 15:27 UTC
In Anserini the log during indexing shows the percentage of documents that have been indexed every minute. This percentage is determined by looking how many files have been indexed. As the WaPo collection is one file with every line being a document the progess shown in the log shows 0% until indexing has finished.

**Comment by lintool** [comment] 2019-09-07 16:01
Acknowledged. Yes, this is a known issue, but lower priority in terms of fixing?

**Comment by Chriskamphuis** [comment] 2019-09-08 13:30
> Acknowledged. Yes, this is a known issue, but lower priority in terms of fixing?

Agree, just made an issue in case it was an unknown problem.

**Comment by lintool** [comment] 2019-10-01 18:45
Duplicate of #683 - closing.

**Closed by lintool** 2019-10-01 18:45 UTC
